name: TheMonkeyPack
main: org.simiancage.bukkit.TheMonkeyPack.TheMonkeyPack
version: 0.1
website: http://dev.bukkit.org/server-mods/themonkeypack/
author: Don Redhorse
description: Lot's of stuff.... neat stuff
softdepend: [Vault]

commands:
    tmpadmin:
        description: administer TheMonkeyPack
        usage: |
            /<command>
    tmpkit:
        description: show a list of kit names or get a named kit
        usage: |
            /<command> [kitname] [player]
