name: TheMonkeyPack
main: org.simiancage.bukkit.TheMonkeyPack.TheMonkeyPack
version: 0.10
website: http://dev.bukkit.org/server-mods/themonkeypack/
author: Don Redhorse
description: Lot's of stuff.... neat stuff
softdepend: [Vault]

commands:
    tmpadmin:
        description: administer TheMonkeyPack
        usage: |
            /<command>
    tmpkit:
        description: show a list of kit names or get a named kit
        usage: |
            /<command> [kitname] [player]
    tmpgetpayed:
        description: get price infos and configure some aspects of getpayed.
        usage: |
            /<command> [option]
    tmpworkplace:
        description: configure the workplace
        usage: |
            /<command> [option]
    tmppriceset:
        description: sets the break and place price of the block you rightclick
        usage: |
            /<command> <break|place> <amount>
    tmptnt:
        description: get information about TNT Control
        usage: |
            /<command>

    tmptntreclaim:
        description: toggle reclaiming TNT by punching it
        usage: |
            /<command> [option]

    tmpmemory:
        description: display memory information
        usage: |
            /<command> [option]
