name: TheMonkeyPack
main: org.simiancage.bukkit.TheMonkeyPack.TheMonkeyPack
version: 0.1
website: http://dev.bukkit.org/server-mods/themonkeypack/
author: Don Redhorse
description: Lot's of stuff.... neat stuff
softdepend: [Vault]
